version: '3'

services:
  database:
    container_name: daedongmap-db
    image: mysql/mysql-server:8.0.2-1.0.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: daedongmapdb
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - daedongmap-api

  application:
    container_name: daedongmap-back
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://daedongmap-db:3307/daedongmapdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

    depends_on:
      database:
        condition: service_healthy
    networks:
      - daedongmap-api

networks:
  daedongmap-api:
    driver: bridge