spring:
  application:
    name: daedongmap

  datasource:
    #        H2
#    url: jdbc:h2:mem:daedongmap-db
#    username: sa
#  h2:
#    console:
#      enabled: true

  #        MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://daedongmap-db.cd8ayw8my9fr.ap-northeast-2.rds.amazonaws.com:3306/daedongmap?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username:
      password:

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  
  #  설정 파일 생성 시 까먹지 말고 include 하기
  profiles:
    include: aws, oauth, secret
