spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: wjaK1ygz0kdgk4kLHjcA
            client-secret: CrFCI9IKlD
            redirect-uri: http://localhost:8080/login/oauth2/naver
            authorization-grant-type: authorization_code
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response